plugins { id 'com.android.application' }
android {
    namespace 'com.shocos.asistente'
    compileSdk 34
    defaultConfig { applicationId "com.shocos.asistente"; minSdk 26; targetSdk 34; versionCode 16; versionName "16-final" }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    buildTypes { debug { minifyEnabled false } }
}
dependencies {}
