plugins { id 'com.android.application' }
android {
    namespace 'com.shocos.asistente'
    compileSdk 34
    defaultConfig {
        applicationId "com.shocos.asistente"
        minSdk 26
        targetSdk 34
        versionCode 20
        versionName "20-release-limpio-final"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES','META-INF/LICENSE','META-INF/LICENSE.txt','META-INF/NOTICE','META-INF/NOTICE.txt']
        }
    }
    signingConfigs {
        release {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
dependencies {}
